# Generated by Django 3.2.7 on 2021-10-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='default_image.png', upload_to='product image/'),
        ),
    ]
