# Generated by Django 3.2.7 on 2021-10-06 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_rename_short_description_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='product_description',
        ),
    ]
