# Generated by Django 3.2.7 on 2021-10-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_rename_description_product_product_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
