# Generated by Django 3.2.7 on 2021-10-17 19:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0018_remove_product_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='profile_image'),
            preserve_default=False,
        ),
    ]
